const Menu = [
  {
    id: 1,
    image: "images/allupakoida.jpg",
    name: "allupakoida",
    category: "breakfast",
    price: "20₹",
    description: "allupakoida is a product in this category",
  },
  {
    id: 2,
    image: "images/chola.jpg",
    name: "chola",
    category: "breakfast",
    price: "50₹",
    description: "chola is a product in this category",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "evening",
    price: "30₹",
    description: "corn is a product in this category",
  },
  {
    id: 4,
    image: "images/maggi.jpg",
    name: "maggi",
    category: "evening",
    price: "35₹",
    description: "maggi is a product in this category",
  },
  {
    id: 5,
    image: "images/momo.jpg",
    name: "momo",
    category: "lunch",
    price: "100₹",
    description: "momo is a product in this category",
  },
  {
    id: 6,
    image: "images/pizza.jpg",
    name: "pizza",
    category: "lunch",
    price: "150₹",
    description: "pizza is a product in this category",
  },
  {
    id: 7,
    image: "images/puri.jpg",
    name: "puri",
    category: "lunch",
    price: "70₹",
    description: "puri is a product in this category",
  },
  {
    id: 8,
    image: "images/rajmarice.jpg",
    name: "rajmarice",
    category: "lunch",
    price: "200₹",
    description: "rajmarice is a product in this category",
  },
  {
    id: 9,
    image: "images/rotiwithmeat.jpg",
    name: "rotiwithmeat",
    category: "lunch",
    price: "250₹",
    description: "rotiwithmeat is a product in this category",
  },
  //   {
  //       id:10,
  //       image:"images/samosa.jpg";
  //       name: "samosa",
  //       category: "breakfast",
  //       price: "10₹",
  //       description: "samosa is a product in this category",
  //   },
  {
    id: 11,
    image: "images/nonvegthali.jpg",
    name: "nonvegthali",
    category: "lunch",
    price: "330₹",
    description: "nonvegthali is a product in this category",
  },
];

export default Menu;
